openapi: 3.0.0
info:
  title: Dokumentasi
  version: v1
servers:
  - url: http://localhost:8080/api/v1
  - url: https://skripsi-245802795341.asia-southeast2.run.app/api/v1
tags:
  - name: users
    description: users
  - name : kursus
    description: kursus
  - name : transaksi
    description: transaksi
  - name: profile
    description: profile user
paths:
  /register:
    post:
      tags:
        - users
      summary: Register User
      description: User register, setiap field harus terisi, kalo kosong response nya bad request
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - nomor_hp
                - email
                - password
                - confirm_password
              properties:
                username:
                  type: string
                nomor_hp:
                  type: string
                email:
                  type: string
                password:
                  type: string
                confirm_password:
                  type: string
              example:
                username: test
                nomor_hp: 012345678911
                email: testing@test.com
                password: test123
                confirm_password: test123
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    properties:
                      token:
                        type: string
              example:
                status: true
                message: Register Success
                data: null
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
              examples:
                Empty Field:
                  value:
                    status: false
                    message: <Field> cannot be empty
                    data: null
                Bad Input:
                  value:
                    status: false
                    message: Format data not valid
                    data: null
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  errorType:
                    type: string
                  data:
                    type: array
              examples:
                Email Exist:
                  value:
                    status: false
                    message: Email already exists
                    data: null
                Username Exist:
                  value:
                    status: false
                    message: Username already exists
                    data: null 
  /login:
    post:
      tags:
        - users
      summary: Login User
      description: login register, setiap field harus terisi, kalo kosong response nya bad request
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
              example:
                email: testing@test.com
                password: test123
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    properties:
                      token:
                        type: string
              example:
                status: true
                message: Login Success
                data: null
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
              examples:
                Empty Field:
                  value:
                    status: false
                    message: <Field> cannot be empty
                    data: null
                Bad Input:
                  value:
                    status: false
                    message: Format data not valid
                    data: null
  /forgot:
    post:
      tags:
        - users
      summary: Forgot Password User
      description: proses permintaan lupa password
      operationId: forgot
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
              example:
                email: testing@test.com
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    properties:
                      token:
                        type: string
              example:
                status: true
                message: Success
                data: null
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
              examples:
                Empty Field:
                  value:
                    status: false
                    message: <Field> cannot be empty
                    data: null
                Bad Input:
                  value:
                    status: false
                    message: Format data not valid
                    data: null
  /otp:
    post:
      tags:
        - users
      summary: OTP Forgot Password
      description: OTP Forgot Password, setelah diberikan pesan email yang berisi digit angka OTP 
      operationId: otp
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - otp
              properties:
                otp:
                  type: string
              example:
                otp: 12345
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    properties:
                      token:
                        type: string
              example:
                status: true
                message: Success
                data: null
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
              example:
                status: false
                message: <Field> cannot be empty
                data: null
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  status: false
                  message: Email not Found
                  data: null
  /reset:
    post:
      tags:
        - users
      summary: reset password User
      description: reset password user, setelah berhasil memberikan kode otp
      operationId: reset
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - password
                - confirm_password
              properties:
                password:
                  type: string
                confirm_password:
                  type: string
              example:
                confirm_password: test123
                password: test123
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    properties:
                      token:
                        type: string
              example:
                status: true
                message: Success
                data: null
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
              examples:
                Empty Field:
                  value:
                    status: false
                    message: <Field> cannot be empty
                    data: null
                Bad Input:
                  value:
                    status: false
                    message: Format data not valid
                    data: null
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  status: false
                  message: Email not Found
                  data: null
  /kursus:
    get:
      tags:
        - kursus
      summary: Menampilkan seluruh data kursus
      description: Menampilkan seluruh data kursus
      operationId: getkursus
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        nama:
                          type: string
                        deskripsi:
                          type: string
                        image: 
                          type: array
                          items: 
                            type: object
                            properties:
                              nama: 
                                type: string
                              url:
                                type: string
                              position:
                                type: integer
                        harga:
                          type: integer
                        jadwal:
                          type: array
                          items: 
                            type: object
                            properties:
                              hari: 
                                type: string
                              jam_mulai:
                                type: string
                              jam_selesai:
                                type: string
                example:
                  status: true
                  message: Get kursus Success
                  metadata: 
                    type: a
                  data:
                    - id: "86265355-f2a4-4acd-8195-6e56de7aba56"
                      nama: "Corel"
                      deskripsi: "Corel"
                      image:
                        - nama: "Corel"
                          url: "https://test.com"
                          position: 1
                        - nama: "Corel"
                          url: "https://test2.com"
                          position: 2
                      harga: 1500000
                      jadwal:
                        - hari: "Senin"
                          jam_mulai: "16:00"
                          jam_selesai: "18:00"
                        - hari: "Selasa"
                          jam_mulai: "16:00"
                          jam_selesai: "18:00"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  status: false
                  message: Unauthorized
                  data: null
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                example:
                  status: false
                  message: User not found
                  data: null 
  /kursus/{kursus_id}:
    get:
      tags:
        - kursus
      summary: Menampilkan data kursus by id
      description: Menampilkan data kursus by id
      operationId: getKursusbyid
      security:
        - bearerAuth: []
      parameters:
        - name: kursus_id
          in: path
          required: true
          schema:
            type: string
          example: 005c310b-015a-4075-b3b5-575b1feb14d6
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        nama:
                          type: string
                        deskripsi:
                          type: string
                        image: 
                          type: array
                          items: 
                            type: object
                            properties:
                              nama: 
                                type: string
                              url:
                                type: string
                              position:
                                type: integer
                        harga:
                          type: integer
                        jadwal:
                          type: array
                          items: 
                            type: object
                            properties:
                              hari: 
                                type: string
                              jam_mulai:
                                type: string
                              jam_selesai:
                                type: string
                example:
                  status: true
                  message: Get kursus Success
                  data:
                      id: "86265355-f2a4-4acd-8195-6e56de7aba56"
                      nama: "Corel"
                      deskripsi: "Corel"
                      image:
                        - nama: "Corel"
                          url: "https://test.com"
                          position: 1
                        - nama: "Corel"
                          url: "https://test2.com"
                          position: 2
                      harga: 1500000
                      jadwal:
                        - hari: "Senin"
                          jam_mulai: "16:00"
                          jam_selesai: "18:00"
                        - hari: "Selasa"
                          jam_mulai: "16:00"
                          jam_selesai: "18:00"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  status: false
                  message: Unauthorized
                  data: null
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                example:
                  status: false
                  message: User not found
                  data: null 
  /kursus/search:
    get:
      tags:
        - kursus
      summary: Menampilkan data kursus berdasarkan nama
      description: Endpoint ini menampilkan data kursus berdasarkan pencarian dengan parameter nama.
      operationId: getKursusByName
      security:
        - bearerAuth: []
      parameters:
        - name: name
          in: query
          description: Nama kursus yang ingin dicari
          required: true
          schema:
            type: string
          example: corel
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        nama:
                          type: string
                        deskripsi:
                          type: string
                        image:
                          type: array
                          items:
                            type: object
                            properties:
                              nama:
                                type: string
                              url:
                                type: string
                              position:
                                type: integer
                        harga:
                          type: integer
                        jadwal:
                          type: array
                          items:
                            type: object
                            properties:
                              hari:
                                type: string
                              jam_mulai:
                                type: string
                              jam_selesai:
                                type: string
                example:
                  status: true
                  message: Get kursus Success
                  data:
                    - id: "86265355-f2a4-4acd-8195-6e56de7aba56"
                      nama: "Corel"
                      deskripsi: "Pelatihan Corel untuk pemula"
                      image:
                        - nama: "Corel"
                          url: "https://test.com/image1.jpg"
                          position: 1
                        - nama: "Corel"
                          url: "https://test2.com/image2.jpg"
                          position: 2
                      harga: 1500000
                      jadwal:
                        - hari: "Senin"
                          jam_mulai: "16:00"
                          jam_selesai: "18:00"
                        - hari: "Selasa"
                          jam_mulai: "16:00"
                          jam_selesai: "18:00"
  /voucher:
    get:
      tags:
        - voucher
      summary: Menampilkan seluruh voucher yang ada
      description: Menampilkan seluruh data mengenai voucher yang tersedia
      operationId: getVoucher
      security:
        - bearerAuth: []
      responses:
          "200":
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: boolean
                    message:
                      type: string
                    data:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                          nama:
                            type: string
                          code:
                            type: string
                          discount: 
                            type: integer
                          expired_at:
                            type: string
                  example:
                    status: true
                    message: Get Voucher Success
                    metadata: 
                      type: a
                    data:
                      - id: "15270598-8731-41ea-b3a3-12e18ef14206"
                        nama: "Voucher Awal Tahun"
                        code: "ZLsSmWQb24"
                        discount: 5,
                        expired_at: "2025-01-07T23:59:59Z"
                        
          "401":
            description: Unauthorized
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                  example:
                    status: false
                    message: Unauthorized
                    data: null
          "404":
            description: Not Found
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: boolean
                    message:
                      type: string
                  example:
                    status: false
                    message: Data not found
                    data: null 
  /voucher/{voucher_id}:
    get:
      tags:
        - voucher
      summary: Menampilkan seluruh voucher yang ada
      description: Menampilkan seluruh data mengenai voucher yang tersedia
      operationId: getVoucherbyid
      security:
        - bearerAuth: []
      parameters:
        - name: voucher_id
          in: path
          required: true
          schema:
            type: string
          example: 15270598-8731-41ea-b3a3-12e18ef14206
      responses:
          "200":
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: boolean
                    message:
                      type: string
                    data:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                          nama:
                            type: string
                          code:
                            type: string
                          discount: 
                            type: integer
                          expired_at:
                            type: string
                  example:
                    status: true
                    message: Get Voucher Success
                    metadata: 
                      type: a
                    data:
                      - id: "15270598-8731-41ea-b3a3-12e18ef14206"
                        nama: "Voucher Awal Tahun"
                        code: "ZLsSmWQb24"
                        discount: 5,
                        expired_at: "2025-01-07T23:59:59Z"
                        
          "401":
            description: Unauthorized
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                  example:
                    status: false
                    message: Unauthorized
                    data: null
          "404":
            description: Not Found
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: boolean
                    message:
                      type: string
                  example:
                    status: false
                    message: Data not found
                    data: null 
  /profile:
    get:
      tags:
          - profile
      summary: Menampilkan seluruh voucher yang ada
      description: Menampilkan seluruh data mengenai voucher yang tersedia
      operationId: getProfile
      security:
        - bearerAuth: []
      responses:
          "200":
              description: OK
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      status:
                        type: boolean
                      message:
                        type: string
                      data:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                            nis:
                              type: string
                            username:
                              type: string
                            nama: 
                              type: string
                            email: 
                              type: string
                            nomor_hp : 
                              type: string
                            agama:
                              type: string
                            gender:
                              type: string
                            tempat_lahir:
                              type: string
                            tanggal_lahir:
                              type: string
                            orang_tua:
                              type: string
                            profesi:
                              type: string
                            ijazah:
                              type: string
                            ktp:
                              type: string
                            kartu_keluarga: 
                              type: string
                            profile_url: 
                              type: string  
                    example:
                      status: true
                      message: Get Profile Success
                      data:
                          id: "7a9470b7-e05a-4e09-8764-d0b4b97309da"
                          nis: ""
                          username: "Chand"
                          nama: "Chandra"
                          email: "chand@test.com"
                          nomor_hp: "01232421451"
                          agama: "Islam"
                          gender: "laki-laki"
                          tempat_lahir: "Banyumas, Jawa Tengah"
                          tanggal_lahir: "dd-mm-yyyy"
                          orang_tua: "Ibu dan Ayah"
                          profesi: "Mahasiswa"
                          ijazah: "https://storage.googleapis.com/ijazah.png"
                          ktp : "https://storage.googleapis.com/ktp.png"
                          kartu_keluarga: "https://storage.googleapis.com/kartu_keluarga.png"
                          profile_url: "https://storage.googleapis.com/profile.png"
          "401":
              description: Unauthorized
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
                    example:
                      status: false
                      message: Unauthorized
                      data: null
          "404":
              description: Not Found
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      status:
                        type: boolean
                      message:
                        type: string
                    example:
                      status: false
                      message: Data not found
                      data: null 
    put:
      tags:
          - profile
      summary: Menampilkan seluruh voucher yang ada
      description: Menampilkan seluruh data mengenai voucher yang tersedia
      operationId: updateProfile
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - nomor_hp
                - email
                - password
                - confirm_password
              properties:
                username:
                  type: string
                nomor_hp:
                  type: string
                email:
                  type: string
                password:
                  type: string
                confirm_password:
                  type: string
              example:
                username: test
                nomor_hp: 012345678911
                email: testing@test.com
                password: test123
                confirm_password: test123
      responses:
        "201":
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: boolean
                    message:
                      type: string
                    data:
                      type: array
                      properties:
                        token:
                          type: string
                example:
                  status: true
                  message: Register Success
                  data: null
        "401":
              description: Unauthorized
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
                    example:
                      status: false
                      message: Unauthorized
                      data: null

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []